import {expect,test,type Page} from '@playwright/test';
import {writeFileSync} from 'node:fs';
import {signInWorkbench,workspace,project,resetWorkbenchFixtureRateWindows} from './fixtures/workbench-auth';

async function open(page:Page,path='/app',actor:'reviewer'|'access'|'viewer'|'admin'='access'){
 await resetWorkbenchFixtureRateWindows();await signInWorkbench(page,true,actor,`${path}?workspace=${workspace}&project=${project}`);
 await page.getByRole('combobox',{name:/^(Language|語言)$/,exact:true}).first().selectOption('en');
}

test('WF01 latest offer metadata uses bounded one-row pages rather than downloading ICP history',async({page})=>{
 await open(page);await expect(page.getByRole('region',{name:'Profile details',exact:true})).toContainText('Profile version');const calls:{offset:number;limit:number}[]=[];
 page.on('request',request=>{const url=new URL(request.url());if(url.pathname.endsWith(`/projects/${project}/icp-versions`))calls.push({offset:Number(url.searchParams.get('offset')),limit:Number(url.searchParams.get('limit'))});});
 await page.getByRole('button',{name:'Edit offer',exact:true}).click();await expect(page.getByRole('textbox',{name:'Product / service',exact:true})).not.toBeEmpty();
 expect(calls.length).toBeGreaterThan(0);expect(calls.length).toBeLessThanOrEqual(2);expect(calls.every(call=>call.limit===1)).toBe(true);
 writeFileSync('test-results/q09-latest-offer.json',JSON.stringify({fixture_only:true,calls},null,2));
});

test('U09 no selection hides batch forms; explicit selection exposes a sticky named action summary',async({page})=>{
 await open(page,'/app/discover');const buyers=page.getByRole('region',{name:'Buyer results',exact:true});await expect(buyers.getByRole('checkbox',{name:/^Select /})).toHaveCount(12);
 await expect(buyers.getByRole('region',{name:'Assign buyer owners',exact:true})).toHaveCount(0);
 await expect(buyers.getByRole('group',{name:'Selected buyer actions',exact:true})).toHaveCount(0);
 await buyers.getByRole('checkbox',{name:/^Select /}).first().check();
 const actions=buyers.getByRole('group',{name:'Selected buyer actions',exact:true});await expect(actions).toBeVisible();expect(await actions.evaluate(e=>getComputedStyle(e).position)).toBe('sticky');
 await expect(actions).toContainText('1 selected');await actions.getByRole('link',{name:'Selected actions',exact:true}).click();await expect(page.locator('#selected-buyer-tools')).toBeVisible();await expect(page.locator('#selected-buyer-tools')).toContainText('Assign buyer owners');await actions.getByRole('button',{name:'Clear selection',exact:true}).click();await expect(actions).toHaveCount(0);
});

async function offer(page:Page,company:string){
 await page.getByRole('textbox',{name:'Company name',exact:true}).fill(company);await page.getByRole('textbox',{name:'Product / service',exact:true}).fill('Industrial sensors');await page.getByRole('textbox',{name:'Value proposition',exact:true}).fill('Fictional monitoring prevents unexpected downtime.');
 await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('textbox',{name:'Markets (country codes or names)',exact:true}).fill('US');await page.getByRole('textbox',{name:'Languages (codes or names)',exact:true}).fill('en');await page.getByRole('checkbox',{name:'Distributor',exact:true}).check();
 await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('textbox',{name:'Must have',exact:true}).fill('Industrial sensors distributor');await page.getByRole('checkbox',{name:/I confirm these buyer requirements/}).check();await page.getByRole('button',{name:'Continue',exact:true}).click();
}
test('WF01 project-only partial save preserves every input and same intent creates one project and ICP',async({page})=>{
 await open(page);await page.getByRole('button',{name:'New project',exact:true}).click();await offer(page,'Q09 Fictional Partial Seller');
 const projects:{key:string;id:string;body:unknown}[]=[],icps:{key:string;body:unknown;status:number}[]=[];
 await page.route(`**/v1/workspaces/${workspace}/projects`,async route=>{if(route.request().method()!=='POST')return route.continue();const response=await route.fetch();expect(response.status()).toBe(201);projects.push({key:route.request().headers()['idempotency-key'],id:(await response.json()).data.id,body:route.request().postDataJSON()});await route.fulfill({response});});
 await page.route('**/v1/workspaces/*/projects/*/icp-versions',async route=>{if(route.request().method()!=='POST')return route.continue();const row={key:route.request().headers()['idempotency-key'],body:route.request().postDataJSON(),status:500};icps.push(row);if(icps.length===1)return route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({code:'INTERNAL_ERROR',message:'fictional one-shot ICP outage',request_id:'e0090000-0000-4000-8000-000000000001',retryable:true})});const response=await route.fetch();row.status=response.status();await route.fulfill({response});});
 await page.getByRole('button',{name:'Save profile',exact:true}).click();await expect(page.getByText(/Project saved; profile still needs saving/)).toBeVisible();
 const wizard=page.getByRole('region',{name:'Create project',exact:true});await expect(wizard).toHaveAttribute('data-live-unsaved','true');await expect(wizard).toContainText('Q09 Fictional Partial Seller');await expect(wizard).toContainText('Industrial sensors distributor');
 await page.getByRole('button',{name:'Your offer',exact:false}).click();await expect(page.getByRole('textbox',{name:'Company name',exact:true})).toHaveValue('Q09 Fictional Partial Seller');await expect(page.getByRole('textbox',{name:'Product / service',exact:true})).toHaveValue('Industrial sensors');await expect(page.getByRole('textbox',{name:'Value proposition',exact:true})).toHaveValue('Fictional monitoring prevents unexpected downtime.');
 await page.getByRole('button',{name:'Continue',exact:true}).click();await expect(page.getByRole('textbox',{name:'Markets (country codes or names)',exact:true})).toHaveValue('US');await expect(page.getByRole('textbox',{name:'Languages (codes or names)',exact:true})).toHaveValue('en');await expect(page.getByRole('checkbox',{name:'Distributor',exact:true})).toBeChecked();await page.getByRole('button',{name:'Continue',exact:true}).click();await expect(page.getByRole('textbox',{name:'Must have',exact:true})).toHaveValue('Industrial sensors distributor');await expect(page.getByRole('checkbox',{name:/I confirm these buyer requirements/})).toBeChecked();await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByRole('button',{name:'Save profile',exact:true}).click();await expect(page.getByRole('heading',{name:'Profile version 1',exact:false})).toBeVisible();
 expect(projects).toHaveLength(2);expect(projects[1]).toEqual(projects[0]);expect(icps).toHaveLength(2);expect(icps[1].key).toBe(icps[0].key);expect(icps[1].body).toEqual(icps[0].body);expect(icps[1].status).toBe(201);
 const stored=await page.request.get(`http://127.0.0.1:8000/v1/workspaces/${workspace}/projects/${projects[0].id}/icp-versions?offset=0&limit=1`,{headers:{Authorization:'Bearer fixture-access'}});expect(stored.status()).toBe(200);expect((await stored.json()).data.total).toBe(1);
 const list=await page.request.get(`http://127.0.0.1:8000/v1/workspaces/${workspace}/projects?offset=0&limit=100`,{headers:{Authorization:'Bearer fixture-access'}});expect(list.status()).toBe(200);expect((await list.json()).data.items.filter((row:{id:string})=>row.id===projects[0].id)).toHaveLength(1);
 writeFileSync('test-results/q09-wf01.json',JSON.stringify({fixture_only:true,projects,icps},null,2));
});

test('WF02 held reviewer cannot approve the previous offer revision or start research',async({page,browser})=>{
 await open(page);await page.getByRole('button',{name:'New project',exact:true}).click();await offer(page,'Q09 Fictional Stale Seller');await page.getByRole('button',{name:'Save profile',exact:true}).click();await expect(page.getByRole('heading',{name:'Profile version 1',exact:false})).toBeVisible();
 const id=new URL(page.url()).searchParams.get('project')!,ctx=await browser.newContext(),reviewer=await ctx.newPage();
 try{
  await resetWorkbenchFixtureRateWindows();await signInWorkbench(reviewer,false,'reviewer',`/app?workspace=${workspace}&project=${id}`);await reviewer.getByRole('combobox',{name:/^(Language|語言)$/,exact:true}).first().selectOption('en');await expect(reviewer.getByRole('heading',{name:'Profile version 1',exact:false})).toBeVisible();await reviewer.getByRole('checkbox',{name:/Confirm approval of this exact version v1/}).check();
  await page.getByRole('button',{name:'Edit offer',exact:true}).click();await page.getByRole('textbox',{name:'Product / service',exact:true}).fill('Revised sensor platform');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('checkbox',{name:/I confirm these buyer requirements/}).check();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('button',{name:'Save profile',exact:true}).click();await expect(page.getByRole('heading',{name:'Profile version 2',exact:false})).toBeVisible();
  const reply=reviewer.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/approve'));await reviewer.getByRole('button',{name:'Approve profile',exact:true}).click();const denied=await reply;expect(denied.status()).toBe(412);expect((await denied.json()).code).toBe('STALE_REVISION');await expect(reviewer.getByRole('alert').last()).toBeVisible();await expect(reviewer.getByRole('button',{name:'Approve profile',exact:true})).toBeDisabled();await reviewer.getByRole('button',{name:'Reload profile',exact:true}).click();await expect(reviewer.getByText('The offer changed. This profile cannot be approved.',{exact:false})).toBeVisible();
  await page.getByRole('button',{name:'Research runs',exact:true}).click();await expect(page.getByRole('button',{name:'Start research',exact:true})).toBeDisabled();
  const runs=await page.request.get(`http://127.0.0.1:8000/v1/workspaces/${workspace}/projects/${id}/runs?offset=0&limit=1`,{headers:{Authorization:'Bearer fixture-access'}});expect(runs.status()).toBe(200);expect((await runs.json()).data.total).toBe(0);
  writeFileSync('test-results/q09-wf02.json',JSON.stringify({fixture_only:true,project:id,approval_status:denied.status(),research_runs:0},null,2));
 }finally{await ctx.close();}
});

for(const locale of ['en','zh-HK'] as const){
 test(`U10 U11 ${locale} keyboard, named controls, responsive scope and concise announcements`,async({page})=>{
  await open(page,'/app','admin');await page.getByRole('combobox',{name:/^(Language|語言)$/,exact:true}).first().selectOption(locale);await page.emulateMedia({reducedMotion:'reduce'});
  const nav=page.getByRole('navigation',{name:'BuyerOS sections'}),routes=[0,2,3,5,6,7];
  const measures=[];
  for(const index of routes){await nav.getByRole('button').nth(index).click();await expect(page.locator('main')).toBeVisible();
   for(const width of [1280,390]){await page.setViewportSize({width,height:900});expect(await page.locator('.live-scope-grid').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length)).toBe(width===1280?2:1);await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);measures.push({url:page.url(),width,scrollWidth:await page.evaluate(()=>document.documentElement.scrollWidth)});}
   const cdp=await page.context().newCDPSession(page);const tree=await cdp.send('Accessibility.getFullAXTree');expect(tree.nodes.filter((n:{ignored?:boolean;role?:{value?:string};name?:{value?:string}})=>!n.ignored&&['button','textbox','combobox','checkbox','link'].includes(n.role?.value??'')&&!n.name?.value)).toEqual([]);await cdp.detach();
  }
  await nav.getByRole('button').nth(2).click();const buyers=page.getByRole('region',{name:locale==='en'?'Buyer results':'買家結果',exact:true});const details=buyers.getByRole('button',{name:locale==='en'?'Details':'詳情',exact:true}).first();for(let tab=0;tab<80&&!await details.evaluate(e=>e===document.activeElement);tab++)await page.keyboard.press('Tab');await expect(details).toBeFocused();expect(await details.evaluate(e=>getComputedStyle(e).outlineStyle)).not.toBe('none');await page.keyboard.press('Enter');await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(details).toBeFocused();
  await page.getByRole('combobox',{name:/^(Project|專案)$/,exact:true}).selectOption('e9100000-0000-4000-8000-000000000001');await nav.getByRole('button').nth(4).click();await page.locator('.run-list button').filter({hasText:locale==='en'?'completed':'已完成'}).first().click();const article=page.locator('.run-detail');await expect(article).toBeVisible();await expect(article).not.toHaveAttribute('aria-live');await expect(article.getByRole('status')).toHaveCount(1);await expect(article.getByRole('status')).not.toContainText(/Event|事件|Connection|連線/);
  await page.screenshot({path:`test-results/q09-${locale}-390.png`,fullPage:true});writeFileSync(`test-results/q09-${locale}-responsive.json`,JSON.stringify({fixture_only:true,screen_reader:false,measures},null,2));
 });
}

test('U09 manual outcome names, UTC zero denominators and append-only correction survive refresh',async({page})=>{
 await open(page,'/app/results','reviewer');const buyers=page.getByRole('region',{name:'Buyer results',exact:true});await expect(buyers.getByRole('button',{name:'Log outcome',exact:true}).first()).toBeVisible();const first=buyers.locator('.activity').first();const name=await first.locator('b').innerText();await first.getByRole('button',{name:'Log outcome',exact:true}).click();
 const outcomes=page.getByRole('region',{name:'Manual outcomes',exact:true});await expect(outcomes).toContainText(`Selected buyer: ${name}`);await expect(outcomes).toContainText('They do not verify mailbox activity or send a message.');await outcomes.getByRole('textbox',{name:'Outcome notes',exact:true}).fill('Q09 manual fixture reply');const recorded=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname.endsWith('/outcomes'));await outcomes.getByRole('button',{name:'Record manual outcome',exact:true}).click();const original=await (await recorded).json();expect(original.data.source).toBe('manual');expect(original.data.actor_id).toBe('e0000000-0000-4000-8000-000000000004');await expect(outcomes).toContainText('Q09 manual fixture reply');
 const event=outcomes.locator('.activity').filter({hasText:'Q09 manual fixture reply'});await expect(event.locator('code').first()).not.toBeVisible();await expect(event).toContainText(original.data.actor_display_name||'Staff member (name unavailable)');await event.getByRole('button',{name:'Correct event',exact:true}).click();await outcomes.getByRole('combobox',{name:'Outcome stage',exact:true}).selectOption('meeting');await outcomes.getByRole('textbox',{name:'Outcome notes',exact:true}).fill('Q09 corrected manual meeting');await outcomes.getByRole('textbox',{name:'Correction reason',exact:true}).fill('Q09 staff correction after source check');const correcting=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/corrections'));await outcomes.getByRole('button',{name:'Append correction',exact:true}).click();const correction=await (await correcting).json();expect(correction.data.id).not.toBe(original.data.id);expect(correction.data.supersedes_id).toBe(original.data.id);await expect(outcomes).toContainText('Q09 manual fixture reply');await expect(outcomes).toContainText('Q09 corrected manual meeting');
 const usage=page.getByRole('region',{name:'Usage',exact:true});await usage.getByLabel('From UTC',{exact:true}).fill('2025-01-01');await usage.getByLabel('To UTC',{exact:true}).fill('2025-02-01');const metrics=page.waitForResponse(r=>r.request().method()==='GET'&&new URL(r.url()).pathname.endsWith('/usage')&&new URL(r.url()).searchParams.get('from')==='2025-01-01T00:00:00.000Z');await usage.getByRole('button',{name:'Apply period',exact:true}).click();const metric=await (await metrics).json();expect(metric.data.cost_per_accepted_company).toBeNull();expect(metric.data.cost_per_contactable_accepted_company).toBeNull();await expect(usage.locator('.activity').filter({hasText:'Blended cost per accepted company'})).toContainText('—');await page.getByRole('combobox',{name:'Language',exact:true}).first().selectOption('zh-HK');await expect(page.getByRole('region',{name:'使用量',exact:true}).getByLabel('開始日期（UTC）',{exact:true})).toHaveValue('2025-01-01');
 await page.reload();await expect(page.locator('html')).toHaveAttribute('lang','zh-HK');await page.getByRole('button',{name:'登入',exact:true}).click();await expect(page.getByRole('region',{name:/^(Manual outcomes|人手記錄成果)$/,exact:true})).toContainText('Q09 manual fixture reply');await expect(page.getByRole('region',{name:/^(Manual outcomes|人手記錄成果)$/,exact:true})).toContainText('Q09 corrected manual meeting');writeFileSync('test-results/q09-manual-outcome.json',JSON.stringify({fixture_only:true,original,correction,metric},null,2));
});
