import {moduleUrl} from './ts-loader.mjs';
import assert from 'node:assert/strict';
const {seed,base}=await import(moduleUrl('data/demo/fixtures.ts'));
const {quote,confirm,usage,block,csv,httpClient}=await import(moduleUrl('services/mock-client.ts'));
const {advanceRun,cancelRun,retryRun}=await import(moduleUrl('services/run-engine.ts'));
let checks=0;function test(name,fn){fn();checks++;console.log('PASS '+name)}
test('24 distinct fictional companies, 14/6/4 fit distribution',()=>{const s=seed();assert.equal(new Set(s.companies.map(c=>c.id)).size,24);assert.deepEqual(['Match','Needs review','Not a match'].map(f=>s.companies.filter(c=>c.fit===f).length),[14,6,4]);});
test('Suppression, acceptance, suitability, policy and researched status block lookup independently',()=>{const c={...seed().companies[1],review:'Accepted'};assert.equal(block(c),null);for(const p of [{suppressed:true},{review:'Awaiting review'},{fit:'Needs review'},{policy:'Unknown'},{contact:'Catch-all'}])assert.ok(block({...c,...p}));});
function reserved(){let s=seed();s.companies[1].review='Accepted';const q=quote(s,['buyer-2']);s.quotes.push(q);return {s,q}}
test('Lookup reserves budget, charges once, counts distinct companies',()=>{const {s,q}=reserved();assert.equal(usage(s).reserved,.3);let next=confirm(s,q.id);assert.equal(usage(next).reserved,0);assert.equal(usage(next).contactSpent,.3);assert.equal(next.companies[1].contact,'Provider-marked valid');assert.deepEqual(confirm(next,q.id),next);assert.equal(usage(next).accepted,6);});
test('Expired, cancelled and newly suppressed quotes cannot charge',()=>{for(const mode of ['expired','cancelled','suppressed']){let {s,q}=reserved();if(mode==='expired')q.expiresAt='2000-01-01T00:00:00Z';if(mode==='cancelled')q.status='Cancelled';if(mode==='suppressed')s.companies[1].suppressed=true;const n=confirm(s,q.id);assert.equal(usage(n).contactSpent,0);assert.equal(usage(n).reserved,0);}});
test('Budget reduction blocks outstanding quote',()=>{let {s,q}=reserved();s.budget=.1;assert.equal(usage(confirm(s,q.id)).contactSpent,0)});
test('CSV escapes delimiters and formulas and marks demo records',()=>{const c={...seed().companies[0],name:'=HYPERLINK("danger")',why:'a,b\n"quoted"'};const out=csv([c]);assert.ok(out.includes('"\'=HYPERLINK(""danger"")"'));assert.ok(out.includes('"a,b\n""quoted"""'));assert.ok(out.endsWith('"demo"'));});
function running(scenario='Completed sample',budget=10,target=24){let s=seed();s.runs=[{...base,id:'test-run',status:'Running',stage:0,count:0,rawCount:0,scenario,budget,startedAt:new Date().toISOString(),profileVersion:2,target}];return s;}
test('Cancel retains partial results; retry finishes without duplicate events or cost',()=>{let s=running();for(let i=0;i<3;i++)s=advanceRun(s,'test-run');assert.equal(s.runs[0].count,8);s=cancelRun(s,'test-run');assert.equal(s.runs[0].count,8);assert.deepEqual(advanceRun(s,'test-run'),s);s=retryRun(s,'test-run');for(let i=0;i<4;i++)s=advanceRun(s,'test-run');assert.equal(s.runs[0].status,'Completed');assert.equal(s.runs[0].count,24);assert.equal(new Set(s.costs.map(c=>c.eventId)).size,s.costs.length);assert.equal(s.costs.filter(c=>c.eventId.startsWith('test-run:')).reduce((a,c)=>a+c.amount,0),2.4)});
test('Failed stage retries deterministically with retained results',()=>{let s=running('Partial failure');for(let i=0;i<5;i++)s=advanceRun(s,'test-run');assert.equal(s.runs[0].status,'Failed');assert.equal(s.runs[0].count,16);s=retryRun(s,'test-run');for(let i=0;i<3;i++)s=advanceRun(s,'test-run');assert.equal(s.runs[0].status,'Completed');assert.equal(s.costs.filter(c=>c.eventId.startsWith('test-run:')).length,4)});
test('Unavailable provider returns a recoverable state and no candidates',()=>{let s=running('Provider unavailable');s=advanceRun(advanceRun(s,'test-run'),'test-run');assert.equal(s.runs[0].status,'Provider unavailable');assert.equal(s.runs[0].count,0)});
test('Budget cap pauses before spend and target bounds are respected',()=>{let s=running('Completed sample',0);for(let i=0;i<6;i++)s=advanceRun(s,'test-run');assert.equal(s.runs[0].status,'Paused at budget cap');assert.equal(s.runs[0].count,0);assert.equal(s.costs.filter(c=>c.eventId.startsWith('test-run:')).length,0);s=running('Completed sample',10,5);for(let i=0;i<6;i++)s=advanceRun(s,'test-run');assert.equal(s.runs[0].count,5)});
await assert.rejects(()=>httpClient.request(),e=>e.code==='NOT_CONFIGURED'&&!!e.requestId);console.log('PASS live adapter explicitly rejects with structured error');checks++;
console.log(`${checks} domain checks passed`);
