import assert from 'node:assert/strict';
import {test} from 'node:test';
import {mkdtempSync,writeFileSync,readFileSync,existsSync,rmSync,symlinkSync} from 'node:fs';
import {rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {removeOwnedRuntimeRoot} from '../scripts/neon-runtime-cleanup.mjs';
function fixture(){const root=mkdtempSync(join(tmpdir(),'buyeros-n00-runtime-'));const owner={fixture_only:true,runId:'aa11bb22cc33',pid:process.pid,target:'portable',scenario:'valid',private_root:root};writeFileSync(join(root,'owner.json'),JSON.stringify(owner));writeFileSync(join(root,'wrangler.json'),'fictional-private-configuration');return {root,owner};}
function dispose(root){if(existsSync(root))rmSync(root,{recursive:true,force:true,maxRetries:3});}
test('owned cleanup removes private configuration and keeps marker through a transient state failure',async()=>{const {root,owner}=fixture();writeFileSync(join(root,'state'),'fictional-state');let failed=false;try{const proof=await removeOwnedRuntimeRoot(root,owner,{pause:async()=>{},remove:async(path,options)=>{if(path===join(root,'state')&&!failed){failed=true;assert.equal(existsSync(join(root,'wrangler.json')),false);assert.deepEqual(JSON.parse(readFileSync(join(root,'owner.json'),'utf8')),owner);throw Object.assign(new Error('busy'),{code:'EPERM'});}await rm(path,options);}});assert.equal(failed,true);assert.equal(proof.removed,true);assert.equal(proof.transient_errors[0].code,'EPERM');assert.equal(existsSync(root),false);}finally{dispose(root);}});
test('cleanup rejects a mismatched owner before deleting configuration',async()=>{const {root,owner}=fixture();try{await assert.rejects(removeOwnedRuntimeRoot(root,{...owner,runId:'dd11bb22cc33'}),/N00_PROBE_OWNER/);assert.equal(existsSync(join(root,'wrangler.json')),true);}finally{dispose(root);}});
test('cleanup refuses an unreviewed entry before deleting owned configuration',async()=>{const {root,owner}=fixture();writeFileSync(join(root,'unrelated.txt'),'preserve');try{await assert.rejects(removeOwnedRuntimeRoot(root,owner),/N00_PROBE_ROOT_ENTRIES/);assert.equal(existsSync(join(root,'wrangler.json')),true);}finally{dispose(root);}});
test('cleanup deadline retains the owner while private configuration is removed',async()=>{const {root,owner}=fixture();writeFileSync(join(root,'state'),'fictional-state');let time=0;try{await assert.rejects(removeOwnedRuntimeRoot(root,owner,{now:()=>time,pause:async()=>{time+=1000;},timeoutMs:1000,remove:async(path,options)=>{if(path===join(root,'state'))throw Object.assign(new Error('busy'),{code:'EBUSY'});await rm(path,options);}}),/N00_PROBE_ROOT_TIMEOUT/);assert.equal(existsSync(join(root,'owner.json')),true);assert.equal(existsSync(join(root,'wrangler.json')),false);}finally{dispose(root);}});
test('cleanup propagates non-transient IO errors without deleting ownership',async()=>{const {root,owner}=fixture();try{await assert.rejects(removeOwnedRuntimeRoot(root,owner,{remove:async()=>{throw Object.assign(new Error('io'),{code:'EIO'});}}),{code:'EIO'});assert.equal(existsSync(join(root,'owner.json')),true);}finally{dispose(root);}});
test('cleanup rejects a root symlink and preserves its target',async()=>{const {root,owner}=fixture(),alias=root+'-alias';symlinkSync(root,alias,process.platform==='win32'?'junction':'dir');try{await assert.rejects(removeOwnedRuntimeRoot(alias,{...owner,private_root:alias}),/N00_PROBE_ROOT/);assert.equal(existsSync(join(root,'wrangler.json')),true);}finally{rmSync(alias);dispose(root);}});
