import assert from 'node:assert/strict';
import {test} from 'node:test';
import {fixtureBuildProfile} from '../scripts/neon-compatibility-harness.mjs';
const boundary=await import('../scripts/neon-runtime-flow-transport.mjs').catch(()=>({}));
const cfg=()=>({projectId:'fictional-probe-project-123456',branchId:'fictional-probe-branch-123456',authId:'fictional-probe-auth-123456',fingerprint:'a'.repeat(64),sdk:{baseUrl:'https://flow.fixture.invalid/auth'},trust:{issuer:'https://issuer.fixture.invalid',jwksUrl:'https://flow.fixture.invalid/auth/jwks',audience:'fictional-probe-audience'}});
function install(host,config=cfg()){assert.equal(typeof boundary.installFlowFixtureTransport,'function','fixture transport is not implemented');return boundary.installFlowFixtureTransport(config,host);}
test('runtime flow builds in a fresh area with shared strict runtime and separate diagnostic/fixture overlays',()=>{const p=fixtureBuildProfile('runtime-flow');assert.equal(p.area,'test-results/neon-runtime-flow');assert.deepEqual(p.overlays,['tests/fixtures/neon-real-runtime/overlay','tests/fixtures/neon-runtime-flow/overlay','tests/fixtures/neon-runtime-flow-transport/overlay']);assert.equal(p.rscEntry,'./lib/neon-runtime-flow/rsc-service.ts');});
test('allowed SDK session/token/JWKS calls preserve method/body/cookies through the counted loopback URL',async()=>{const seen=[];const host={fetch:async(...args)=>{seen.push(args);return new Response('{"fixture":true}');}};const transport=install(host);for(const path of ['get-session?disableCookieCache=true','token','jwks'])await host.fetch('https://flow.fixture.invalid/auth/'+path,{headers:{cookie:'fictional-cookie'}});assert.equal(seen.length,3);assert.equal(String(seen[0][0]),'http://127.0.0.1:44891/fixture/auth/get-session?disableCookieCache=true');assert.equal(seen[0][1].redirect,'manual');assert.equal(seen[0][1].headers.get('cookie'),'fictional-cookie');assert.equal(transport.metrics().forwarded,3);assert.equal(transport.metrics().external_requests,0);});
test('fixture transport supports Request inputs without leaking a new endpoint',async()=>{let body;const host={fetch:async(url,options)=>{assert.equal(String(url),'http://127.0.0.1:44891/fixture/auth/sign-in/social');body=await new Request(url,options).text();return new Response('{}');}};install(host);await host.fetch(new Request('https://flow.fixture.invalid/auth/sign-in/social',{method:'POST',body:'{"provider":"google"}',headers:{Origin:'http://localhost:44890'}}));assert.equal(body,'{"provider":"google"}');});
test('foreign origin, credentials, encoded path, unknown endpoint and loopback bypass never dispatch',async()=>{let called=0;const host={fetch:async()=>{called++;return new Response('{}');}};const transport=install(host);for(const url of ['https://auth.neon.tech/auth/token','https://u:p@flow.fixture.invalid/auth/token','https://flow.fixture.invalid/auth/%74oken','https://flow.fixture.invalid/auth/admin/create-user','http://127.0.0.1:44894/fixture/auth/token','https://flow.fixture.invalid/auth/token#fragment'])await assert.rejects(host.fetch(url),/N00_FLOW_FETCH_REFUSED/);assert.equal(called,0);assert.equal(transport.metrics().blocked,6);});
test('transport cannot be installed for real targets or rebound to different fictional context',()=>{const host={fetch:async()=>new Response('{}')};install(host);assert.throws(()=>install(host,{...cfg(),fingerprint:'b'.repeat(64)}),/N00_FLOW_CONTEXT_CHANGED/);assert.throws(()=>install({fetch:async()=>new Response('{}')},{...cfg(),projectId:'real-project-123456'}),/N00_PROBE_FICTIONAL_ONLY/);});
test('unknown upstream response is surfaced once without retry',async()=>{let called=0;const host={fetch:async()=>{called++;throw new Error('connection lost');}};install(host);await assert.rejects(host.fetch('https://flow.fixture.invalid/auth/sign-in/social',{method:'POST',body:'{}'}),/connection lost/);assert.equal(called,1);});
test('SDK POST redirect is returned to the caller and is never automatically followed',async()=>{let called=0;const host={fetch:async(url,options)=>{called++;assert.equal(options.redirect,'manual');return new Response(null,{status:302,headers:{location:'https://external.invalid'}});}};install(host);assert.equal((await host.fetch('https://flow.fixture.invalid/auth/sign-out',{method:'POST'})).status,302);assert.equal(called,1);});

test('owned diagnostic is the only additional loopback transport and requires its exact private owner nonce',async()=>{assert.equal(typeof boundary.installFlowFixtureTransport,'function');let calls=0;const host={fetch:async(url)=>{calls++;assert.equal(url,'http://127.0.0.1:44892/verify');return new Response('{}');}};const nonce='x'.repeat(43);boundary.installFlowFixtureTransport(cfg(),host,nonce);await assert.rejects(host.fetch('http://127.0.0.1:44892/verify',{headers:{'x-n00-owner':'wrong'}}),/N00_FLOW_FETCH_REFUSED/);await host.fetch('http://127.0.0.1:44892/verify',{headers:{'x-n00-owner':nonce}});assert.equal(calls,1);});
