import assert from 'node:assert/strict';
import {test} from 'node:test';
import {readFileSync} from 'node:fs';
import {executionFixture} from './fixtures/neon-execution/fixture.mjs';
import {createFixtureExecutionBoundary} from '../scripts/neon-execution-boundary.mjs';
const adapter=await import('../scripts/neon-cleanup-contracts.mjs').catch(error=>{if(error.code!=='ERR_MODULE_NOT_FOUND')throw error;return {};});
const stamp=()=>new Date().toISOString();
function bodies(target){return {project:{project:{id:target.projectId,name:target.name,region_id:target.regionId,owner_id:target.orgId,platform_id:'aws',created_at:target.createdAt,owner:{email:'must-not-leak@example.invalid'}}},auth:{auth_provider:'better_auth',auth_provider_project_id:target.authId,branch_id:target.branchId,owned_by:'neon',created_at:target.createdAt,jwks_url:target.auth.jwksUrl,base_url:target.auth.baseUrl,db_name:'must-not-leak'}};}
async function prepare(t){assert.equal(typeof adapter.planNeonCleanup,'function');const f=await executionFixture();t.after(()=>f.cleanup());const b=bodies(f.target),url='https://console.neon.tech/api/v2/projects/'+f.target.projectId;return {...f,input:{journal:f.journal,projectRead:{method:'GET',url,status:200,body:b.project,receivedAt:stamp()},authRead:{method:'GET',url:url+'/branches/'+f.target.branchId+'/auth',status:200,body:b.auth,receivedAt:stamp()}}};}
test('official project/auth requests bind exact resource, no credentials or deletion executor',async t=>{const f=await prepare(t),r=adapter.planNeonCleanup(f.input);assert.equal(r.external_authorized,false);assert.equal(r.external_verified,false);assert.equal(r.execution_enabled,false);assert.equal(r.blocked,'external-transport-and-authority-required');assert.deepEqual(r.resources.map(v=>v.kind),['auth','project']);assert.equal(r.resources[0].delete.method,'DELETE');assert.equal(r.resources[0].delete.url,f.input.authRead.url);assert.equal(r.resources[0].delete.body,'{"delete_data":false}');assert.equal(r.resources[1].delete.url,f.input.projectRead.url);assert.equal(r.project_recovery_window_days,7);assert.equal(r.identity_erasure_verified,false);assert.doesNotMatch(JSON.stringify(r),/must-not-leak|Authorization|Bearer/);assert.equal(f.journal.snapshot().requests.length,0);});
for(const [label,change]of [['projectID',f=>f.input.projectRead.body.project.id='nameless-bar-15324691'],['owner',f=>f.input.projectRead.body.project.owner_id='foreign-org'],['conflicting-org',f=>f.input.projectRead.body.project.org_id='foreign-org'],['region',f=>f.input.projectRead.body.project.region_id='aws-us-east-1'],['name',f=>f.input.projectRead.body.project.name='other'],['project-time',f=>f.input.projectRead.body.project.created_at=new Date(Date.parse(f.target.createdAt)-1000).toISOString()],['provider',f=>f.input.authRead.body.auth_provider='stack'],['authID',f=>f.input.authRead.body.auth_provider_project_id='other'],['branch',f=>f.input.authRead.body.branch_id='other'],['ownership',f=>f.input.authRead.body.owned_by='user'],['JWKS',f=>f.input.authRead.body.jwks_url='https://foreign.invalid/jwks'],['baseURL',f=>f.input.authRead.body.base_url='https://foreign.invalid/auth'],['auth-time',f=>f.input.authRead.body.created_at=new Date(Date.parse(f.target.createdAt)-1000).toISOString()]])test('mismatched '+label+' refuses a cleanup plan',async t=>{const f=await prepare(t);change(f);assert.throws(()=>adapter.planNeonCleanup(f.input),/N00_CLEANUP_/);assert.equal(f.journal.snapshot().requests.length,0);});
for(const status of [301,401,403,404,423,429,500,503])test('HTTP '+status+' is not ownership or absence proof',async t=>{const f=await prepare(t);f.input.authRead.status=status;assert.throws(()=>adapter.planNeonCleanup(f.input),/READBACK/);});
for(const [label,change]of [['stale',f=>f.input.projectRead.receivedAt=new Date(Date.now()-300001).toISOString()],['future',f=>f.input.authRead.receivedAt=new Date(Date.now()+60000).toISOString()],['wrong-path',f=>f.input.authRead.url+='/users'],['foreign-origin',f=>f.input.projectRead.url='https://foreign.invalid/api/v2/projects/'+f.target.projectId],['query',f=>f.input.projectRead.url+='?redirect=1'],['wrong-method',f=>f.input.projectRead.method='DELETE'],['credential-field',f=>f.input.authRead.headers={Authorization:'secret'}]])test(label+' readback refused',async t=>{const f=await prepare(t);change(f);assert.throws(()=>adapter.planNeonCleanup(f.input),/N00_CLEANUP_/);});
test('a bound human identity blocks auth/project deletion; users_sync is not assumed Better Auth',async t=>{const f=await prepare(t);f.journal.bindIdentity(f.identity);const r=adapter.planNeonCleanup(f.input);assert.equal(r.blocked,'managed-identity-cleanup-contract-unverified');assert.deepEqual(r.resources.map(v=>v.kind),['auth','project']);assert.ok(r.resources.every(v=>v.delete===null));assert.equal(r.identity_erasure_verified,false);});
test('owned counted HTTP payloads decode official field names without claiming provider verification',async t=>{assert.equal(typeof adapter.planNeonCleanup,'function');const f=await executionFixture((req,res,{target})=>{const body=bodies(target);if(req.method==='GET'&&req.url.startsWith('/fixture/control/project/')){res.end(JSON.stringify(body.project));return true;}if(req.method==='GET'&&req.url.startsWith('/fixture/control/auth/')){res.end(JSON.stringify(body.auth));return true;}});t.after(()=>f.cleanup());const execution=createFixtureExecutionBoundary({backend:f.backend,journal:f.journal});const responses=[];for(const kind of ['project','auth'])responses.push(await execution.dispatch({channel:'control',method:'GET',path:'/fixture/control/'+kind+'/'+(kind==='project'?f.target.projectId:f.target.authId)}));const url='https://console.neon.tech/api/v2/projects/'+f.target.projectId,r=adapter.planNeonCleanup({journal:f.journal,projectRead:{method:'GET',url,status:responses[0].status,body:JSON.parse(responses[0].body),receivedAt:stamp()},authRead:{method:'GET',url:url+'/branches/'+f.target.branchId+'/auth',status:responses[1].status,body:JSON.parse(responses[1].body),receivedAt:stamp()}});assert.equal(f.model.hits.length,2);assert.deepEqual(f.journal.snapshot().requests.map(v=>v.outcome),['accepted','accepted']);assert.equal(r.external_verified,false);assert.equal(r.execution_enabled,false);assert.ok(f.model.hits.every(v=>v[0]==='GET'));});
test('adapter contains no network, CLI or ambient credential execution path',()=>{const source=readFileSync(new URL('../scripts/neon-cleanup-contracts.mjs',import.meta.url),'utf8');assert.doesNotMatch(source,/\bfetch\s*\(|process\.env|child_process|https?:.*request\s*\(/);});

for(const outcome of ['pending','unknown'])test(outcome+' request keeps deletion descriptors blocked for reconciliation',async t=>{const f=await prepare(t);f.journal.reserveRequest('auth','earlier-write');if(outcome==='unknown')f.journal.settleRequest('earlier-write','unknown','fixture-only-unknown.json');const r=adapter.planNeonCleanup(f.input);assert.equal(r.blocked,'unresolved-request-reconciliation-required');assert.ok(r.resources.every(v=>v.delete===null));assert.equal(f.journal.snapshot().requests.length,1);});
test('cleanup preparation after TTL requires fresh readbacks and preserves expired target',async t=>{const f=await prepare(t),late=Date.parse(f.target.expiresAt)+1;f.input.now=late;f.input.projectRead.receivedAt=f.input.authRead.receivedAt=new Date(late).toISOString();const r=adapter.planNeonCleanup(f.input);assert.equal(r.execution_enabled,false);assert.equal(r.blocked,'external-transport-and-authority-required');assert.equal(f.journal.snapshot().target.expiresAt,f.target.expiresAt);});
test('an unbranded journal and malformed calendar timestamp cannot create descriptors',async t=>{const f=await prepare(t);assert.throws(()=>adapter.planNeonCleanup({...f.input,journal:{snapshot:()=>f.journal.snapshot()}}),/JOURNAL/);f.input.authRead.body.created_at='2026-02-31T00:00:00Z';assert.throws(()=>adapter.planNeonCleanup(f.input),/TIME/);});
