import assert from 'node:assert/strict';
import {test} from 'node:test';
const boundary=await import('../scripts/neon-real-diagnostic.mjs').catch(()=>({}));
const fingerprint='a'.repeat(64),nonce='n'.repeat(43),base='http://localhost:44890';
const env=()=>({N00_DIAGNOSTIC_URL:'http://127.0.0.1:44892/verify',N00_DIAGNOSTIC_NONCE:nonce,N00_DIAGNOSTIC_FINGERPRINT:fingerprint});
const description={fingerprint,external_verified:false};
const request=(token='a.b.c',origin=base)=>new Request(base+'/api/n00/verify',{method:'POST',headers:{origin,authorization:'Bearer '+token}});
function verify(options){assert.equal(typeof boundary.verifyWithOwnedDiagnostic,'function','owned diagnostic bridge not implemented');return boundary.verifyWithOwnedDiagnostic(options);}
test('bridge forwards bearer once to exact owned diagnostic and returns subject without token',async()=>{let calls=0;const response=await verify({environment:env(),description,request:request(),fetch:async(url,options)=>{calls++;assert.equal(url,env().N00_DIAGNOSTIC_URL);assert.equal(options.headers.get('authorization'),'Bearer a.b.c');assert.equal(options.headers.get('x-n00-owner'),nonce);assert.equal(options.redirect,'manual');return Response.json({subject:'fictional-user',fingerprint,protocol_fixture_only:true});}});assert.equal(calls,1);assert.equal(response.status,200);assert.deepEqual(await response.json(),{subject:'fictional-user',fingerprint,protocol_fixture_only:true,external_verified:false});assert.equal(response.headers.get('cache-control'),'no-store');});
test('missing owner config, external endpoint and different fingerprint refuse before HTTP',async()=>{for(const change of [e=>delete e.N00_DIAGNOSTIC_NONCE,e=>e.N00_DIAGNOSTIC_URL='https://api.external.invalid/verify',e=>e.N00_DIAGNOSTIC_FINGERPRINT='b'.repeat(64)]){let calls=0;const environment=env();change(environment);const response=await verify({environment,description,request:request(),fetch:async()=>{calls++;throw new Error('should not dispatch');}});assert.equal(response.status,503);assert.equal(calls,0);}});
test('foreign or missing Origin and invalid bearer refuse before HTTP',async()=>{for(const req of [request('a.b.c','https://foreign.invalid'),new Request(base+'/api/n00/verify',{method:'POST'}),request('opaque-session')]){let calls=0;const response=await verify({environment:env(),description,request:req,fetch:async()=>{calls++;throw new Error('should not dispatch');}});assert.ok([401,403].includes(response.status));assert.equal(calls,0);}});
test('API rejection stays 401 and unknown API result is not retried or exposed',async()=>{for(const status of [401,500,302]){let calls=0;const response=await verify({environment:env(),description,request:request(),fetch:async()=>{calls++;return Response.json({token:'do-not-expose',trace:'private'},{status});}});assert.equal(calls,1);assert.equal(response.status,status===401?401:503);assert.ok(!(await response.text()).includes('private'));}});
test('mismatched response ownership and malformed response fail closed',async()=>{for(const body of [{subject:'user',fingerprint:'b'.repeat(64),protocol_fixture_only:true},{subject:'',fingerprint,protocol_fixture_only:true},{subject:'user',fingerprint,protocol_fixture_only:false}]){const response=await verify({environment:env(),description,request:request(),fetch:async()=>Response.json(body)});assert.equal(response.status,503);}});
test('network failure cannot expose exception data or trigger a retry',async()=>{let calls=0;const response=await verify({environment:env(),description,request:request(),fetch:async()=>{calls++;throw new Error('secret upstream URL');}});assert.equal(calls,1);assert.equal(response.status,503);assert.equal((await response.text()).includes('secret'),false);});

test('browser receipt must match the rendered target and session subject, and cannot claim live verification',()=>{assert.equal(typeof boundary.validDiagnosticReceipt,'function');const expected={fingerprint,subject:'fictional-user'},receipt={...expected,protocol_fixture_only:true,external_verified:false};assert.equal(boundary.validDiagnosticReceipt(receipt,expected),true);for(const value of [null,{...receipt,fingerprint:'b'.repeat(64)},{...receipt,subject:'other'},{...receipt,protocol_fixture_only:false},{...receipt,external_verified:true}])assert.equal(boundary.validDiagnosticReceipt(value,expected),false);});
