import {uid} from '@/lib/id';
import {base} from '@/data/demo/fixtures';
import type {Company,Store,EnrichmentQuote} from './contracts';
export const money=(n:number)=>'USD '+n.toFixed(2);
export function usage(s:Store){const spent=s.costs.reduce((a,c)=>a+c.amount,0);const contactSpent=s.costs.filter(c=>c.category==='Contact lookup').reduce((a,c)=>a+c.amount,0);const reserved=s.quotes.filter(q=>q.status==='Reserved'&&Date.parse(q.expiresAt)>Date.now()).reduce((a,q)=>a+q.cost,0);const accepted=s.companies.filter(c=>c.review==='Accepted');return {spent,contactSpent,reserved,remaining:Math.max(0,s.budget-contactSpent-reserved),accepted:accepted.length,valid:accepted.filter(c=>c.contact==='Provider-marked valid'&&!c.suppressed).length,pending:s.companies.filter(c=>c.review==='Awaiting review').length};}
export function block(c:Company){return c.suppressed?'Suppressed':c.review!=='Accepted'?'Buyer not accepted':c.fit!=='Match'?'Fit review required':c.policy!=='Allowed'?'Lookup policy unknown':c.contact!=='Not researched'?'Already researched':null;}
export function quote(s:Store,ids:string[]):EnrichmentQuote {const eligible=s.companies.filter(c=>ids.includes(c.id)&&!block(c));return {...base,id:uid(),companyIds:eligible.map(c=>c.id),cost:eligible.length*(s.contactUnitPrice??.3),currency:'USD',expiresAt:new Date(Date.now()+300000).toISOString(),status:'Reserved'};}
export function confirm(s:Store,id:string):Store{const q=s.quotes.find(q=>q.id===id);if(!q||q.status!=='Reserved')return s;if(Date.parse(q.expiresAt)<Date.now()||q.companyIds.some(id=>block(s.companies.find(c=>c.id===id)!))||usage(s).contactSpent+q.cost>s.budget)return {...s,quotes:s.quotes.map(x=>x.id===id?{...x,status:'Cancelled'}:x)};return {...s,quotes:s.quotes.map(x=>x.id===id?{...x,status:'Confirmed'}:x),companies:s.companies.map(c=>q.companyIds.includes(c.id)?{...c,contact:(Number(c.id.split('-')[1])%4===0?'Unavailable':Number(c.id.split('-')[1])%3===0?'Catch-all':'Provider-marked valid'),activity:[new Date().toISOString()+' · Sample contact lookup completed.',...c.activity]}:c),costs:s.costs.some(c=>c.eventId===q.id)?s.costs:[...s.costs,{...base,id:'cost-'+q.id,eventId:q.id,category:'Contact lookup',amount:q.cost,currency:'USD'}]};}
export function csv(companies:Company[]){const safe=(v:string)=>'"'+(/^[\s]*[=+@-]/.test(v)?"'"+v:v).replaceAll('"','""')+'"';return ['company,market,fit,fit_rationale,evidence_reference,review_status,contact_status,data_mode',...companies.map(c=>[c.name,c.market,c.fit,c.why,c.evidence.map(e=>e.id).join(';'),c.review,c.contact,'demo'].map(safe).join(','))].join('\r\n');}
export function download(name:string,text:string,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
export const httpClient={request:async():Promise<never>=>{throw {code:'NOT_CONFIGURED',message:'Live services are not connected.',requestId:uid(),retryable:false};}};
