'use client';
import {uid} from '@/lib/id';
import {LiveWorkspace} from './live/workspace-picker';
import {DemoNavigation} from './workspace/navigation';
import {DemoBuyerTable} from './workspace/buyer-table';
import {DemoShellHeader} from './workspace/shell';
import {DemoSourceDialog,DemoConnectionDialog,DemoActionDialog} from './workspace/modals';
import {DemoRouteHeading,DemoOutreachView,DemoDiscoveryRunView,DemoListsView,DemoOverviewView,DemoResultsView,DemoSettingsView,DemoFullBuyerView} from './workspace/route-view';
import {useState,useEffect,useMemo,useRef} from 'react';
import {usePathname,useRouter} from 'next/navigation';
import {SidebarProvider} from '@/components/ui/sidebar';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {toast,Toaster} from 'sonner';
import {Button,Pick} from './ui';
import {BuyerDetail} from './buyers/detail';
import {Wizard,sample,type Offer} from './discovery/wizard';
import {advanceRun,cancelRun,retryRun} from '@/services/run-engine';
import {seed,base} from '@/data/demo/fixtures';
import {usage,quote,confirm,csv,download} from '@/services/mock-client';
import {zh} from '@/locales';
import {LocaleContext} from '@/locales/context';
import type {Store,Company,Evidence,OutreachDraft,SearchRun} from '@/services/contracts';
import {type DataMode,availabilityFor} from '@/services/live/mode';
import {demoEffectsEnabled,emptyStore} from '@/services/live/workspace-logic';
import {readDemoState,writePrefs} from '@/services/live/storage';
import {LiveOverview} from './live/overview';
import {LiveUnavailable} from './live/unavailable';
import {LiveOfferWizard} from './live/offer-wizard';
import {LiveProfilePanel} from './live/profile';
import {LiveBuyers} from './live/buyers';
type FilterPreset = {market:string;type:string;fit:string;review:string;contact:string;sourceType:string;recency:string};
type DemoToolContext = {registerTool?: (definition:unknown, options:{signal:AbortSignal})=>unknown};
export default function Workspace({mode='demo'}:{mode?:DataMode}){const current=usePathname();return current==='/auth/callback'?null:mode==='live'?<LiveWorkspace/>:<DemoWorkspace mode={mode}/>}
function DemoWorkspace({mode='demo'}:{mode?:DataMode}){const [s,setS]=useState<Store>(()=>mode==='demo'?seed():emptyStore()),[loaded,L]=useState(false);const path=usePathname()||'/',router=useRouter();const go=(url:string)=>router.push(url);const t=(x:string)=>s.locale==='zh-HK'?(zh[x]||x):x;
const [sidebarOpen,SidebarOpen]=useState(true);useEffect(()=>{const m=window.matchMedia('(min-width:1024px)');const change=()=>SidebarOpen(m.matches);change();m.addEventListener('change',change);return()=>m.removeEventListener('change',change)},[]);
const buyerTriggerRef=useRef<HTMLElement|null>(null);
const stateRef=useRef(s);useEffect(()=>{stateRef.current=s},[s]);useEffect(()=>{if(!demoEffectsEnabled(mode))return;const context=(document as Document & {modelContext?:DemoToolContext}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'list_demo_buyers',title:'List demo buyers',description:'Read fictional buyers and their distinct fit, review and contact states. Never returns real research.',inputSchema:{type:'object',properties:{market:{type:'string',enum:['Germany','Netherlands','Belgium']}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:unknown){const a=input as {market?:string};if(!a||typeof a!=='object'||Object.keys(a).some(k=>k!=='market')||(a.market&&!['Germany','Netherlands','Belgium'].includes(a.market)))throw new Error('INVALID_INPUT');return stateRef.current.companies.filter(c=>!a.market||c.market===a.market).map(c=>({id:c.id,name:c.name,market:c.market,fit:c.fit,review:c.review,contact:c.contact,dataMode:'demo'}))}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[mode]);
const [q,Q]=useState(''),[market,M]=useState('All markets'),[fit,F]=useState('All fit verdicts'),[review,R]=useState('All reviews'),[contact,C]=useState('All contacts'),[type,T]=useState('All buyer types'),[sourceType,ST]=useState('All sources'),[recency,RC]=useState('Any observation date'),[sort,Sort]=useState('Best fit first'),[page,P]=useState(1),[size,Size]=useState('8'),[selected,Sel]=useState<string[]>([]),[filters,Filters]=useState(false),[optional,Optional]=useState(false),[preset,Preset]=useState<FilterPreset|null>(null);
const [buyerId,B]=useState<string|null>(null),[source,Source]=useState<Evidence|null>(null),[modal,Modal]=useState(''),[actionIds,Ids]=useState<string[]>([]),[reason,Reason]=useState(''),[listName,LN]=useState(''),[listId,LI]=useState('list-1'),[quoteId,QI]=useState<string|null>(null),[quoteExpired,QuoteExpired]=useState(false),[reset,Reset]=useState(false),[offer,OfferSet]=useState<Offer>({...sample}),[activeRun,AR]=useState('sample-run'),[draftId,DI]=useState<string|null>(null),[resultTab,RT]=useState('Outcomes'),[settingsInfo,SI]=useState(''),[savedLocal,SL]=useState(false);
useEffect(()=>{if(!demoEffectsEnabled(mode))return;let cancelled=false;queueMicrotask(()=>{if(cancelled)return;try{const demo=readDemoState(window.localStorage,mode);const raw=demo['buyeros-demo-v1'];if(typeof raw==='string'){const parsed=JSON.parse(raw);if(Array.isArray(parsed.companies)&&Array.isArray(parsed.runs)&&parsed.companies.length===24)setS(parsed);}const draftsRaw=demo['buyeros-drafts-v1'];if(typeof draftsRaw==='string'){const drafts=JSON.parse(draftsRaw);if(Array.isArray(drafts))setS(x=>({...x,drafts:drafts.filter(d=>d.dataMode==='demo'&&d.recipient?.endsWith('.example')).map(d=>({...d,status:'Draft',approvedRevision:undefined,approvedAt:undefined}))}));}const p=demo['buyeros-prefs-v1'];if(typeof p==='string'){const pref=JSON.parse(p);setS(x=>({...x,locale:pref.locale==='zh-HK'?'zh-HK':'en'}));}}catch{}L(true)});return()=>{cancelled=true}},[mode]);
useEffect(()=>{if(!demoEffectsEnabled(mode))return;if(loaded)writePrefs(window.localStorage,mode,{locale:s.locale});document.documentElement.lang=s.locale},[s.locale,loaded,mode]);
useEffect(()=>{let cancelled=false;queueMicrotask(()=>{if(!cancelled){P(1);Sel([])}});return()=>{cancelled=true}},[q,market,fit,review,contact,type,sourceType,recency,size,path]);
const routeRunId=path.startsWith('/app/discover/')?path.split('/')[3]:undefined;
const run=s.runs.find(r=>r.id===(routeRunId&&routeRunId!=='new'?routeRunId:activeRun))||s.runs[0];
useEffect(()=>{if(!demoEffectsEnabled(mode))return;if(run?.status!=='Running')return;const timer=setTimeout(()=>setS(old=>advanceRun(old,run.id)),700);return()=>clearTimeout(timer)},[mode,run?.id,run?.stage,run?.status]);
const u=demoEffectsEnabled(mode)?usage(s):{spent:0,contactSpent:0,reserved:0,remaining:0,accepted:0,valid:0,pending:0},isWizard=path==='/app/discover/new',isBuyers=path==='/app/discover',isLists=path.startsWith('/app/lists'),isOutreach=path.startsWith('/app/outreach'),isResults=path.startsWith('/app/results'),isSettings=path.startsWith('/app/settings'),isOverview=path==='/app',isFull=path.startsWith('/app/buyers/');const listRoute=isLists?path.split('/')[3]:undefined;const currentList=s.lists.find(l=>l.id===(listRoute||listId));const fullBuyer=isFull?s.companies.find(c=>c.id===path.split('/')[3]):undefined;const buyer=s.companies.find(c=>c.id===buyerId);
const rows=useMemo(()=>{if(!demoEffectsEnabled(mode))return [];let r=s.companies;if(!isLists&&run.id!=='sample-run')r=r.slice(0,run.count);if(isLists)r=r.filter(c=>currentList?.members.includes(c.id));return r.filter(c=>(!q||c.name.toLowerCase().includes(q.toLowerCase()))&&(market==='All markets'||c.market===market)&&(type==='All buyer types'||c.type===type)&&(fit==='All fit verdicts'||c.fit===fit)&&(review==='All reviews'||c.review===review)&&(contact==='All contacts'||c.contact===contact)&&(sourceType==='All sources'||c.evidence.some(e=>e.type===sourceType))&&(recency!=='Old sample evidence')).sort((a,b)=>sort==='Name A–Z'?a.name.localeCompare(b.name):['Match','Needs review','Not a match'].indexOf(a.fit)-['Match','Needs review','Not a match'].indexOf(b.fit))},[mode,s.companies,q,market,type,fit,review,contact,sourceType,recency,sort,isLists,currentList,run]);const pageCount=Math.max(1,Math.ceil(rows.length/+size)),pageRows=rows.slice((Math.min(page,pageCount)-1)*+size,Math.min(page,pageCount)*+size);const selectedRows=s.companies.filter(c=>selected.includes(c.id));
function openBuyer(id:string){buyerTriggerRef.current=document.activeElement instanceof HTMLElement?document.activeElement:null;B(id)}
function update(id:string,patch:Partial<Company>){setS(x=>({...x,companies:x.companies.map(c=>c.id===id?{...c,...patch}:c),drafts:x.drafts.map(d=>d.buyerId===id&&('review'in patch||'suppressed'in patch||'policy'in patch)?{...d,status:'Draft',approvedRevision:undefined,revision:d.revision+1}:d)}))}
function reviewed(ids:string[],status:'Accepted'|'Rejected',why:string){setS(x=>({...x,companies:x.companies.map(c=>ids.includes(c.id)?{...c,review:status,activity:[`${new Date().toISOString()} · Willy Lai: ${c.review} → ${status}. ${why}`,...c.activity]}:c),drafts:x.drafts.map(d=>ids.includes(d.buyerId)?{...d,status:'Draft',approvedRevision:undefined,revision:d.revision+1}:d)}));toast.success(t(status));}
function action(name:string,ids:string[]){Ids(ids);if(name==='accept'){reviewed(ids,'Accepted','Evidence reviewed in demo.');return}if(name==='draft'){const c=s.companies.find(c=>c.id===ids[0])!;if(c.suppressed||c.review!=='Accepted'){toast.error('Accept an unsuppressed buyer before drafting.');return}let d=s.drafts.find(d=>d.buyerId===c.id);if(!d){d={...base,id:uid(),buyerId:c.id,recipient:'purchasing@'+c.name.split(' ')[0].toLowerCase()+'.example',subject:'',body:'',revision:1,status:'Draft',policyReviewed:false,sender:'',delivery:'Not connected',followup:'',objective:'Explore distribution partnership',tone:'Professional',language:'English',valueProposition:sample.value};setS(x=>({...x,drafts:[...x.drafts,d!]}))}DI(d.id);B(null);go('/app/outreach');return}if(name==='lookup'){const qt=quote(s,ids);if(!qt.companyIds.length){QI(null);Modal('lookup');return}if(qt.cost>u.remaining){QI(null);Modal('lookup');return}QI(qt.id);QuoteExpired(false);setS(x=>({...x,quotes:[...x.quotes,qt]}));}Modal(name)}
function closeModal(){if(quoteId)setS(x=>({...x,quotes:x.quotes.map(q=>q.id===quoteId&&q.status==='Reserved'?{...q,status:'Cancelled'}:q)}));QI(null);QuoteExpired(false);Modal('');Reason('')}
function clear(){Q('');M('All markets');T('All buyer types');F('All fit verdicts');R('All reviews');C('All contacts');ST('All sources');RC('Any observation date')}
function startRun(){const sampleInput=offer.company===sample.company&&offer.product===sample.product&&offer.value===sample.value&&offer.markets===sample.markets&&offer.must===sample.must&&offer.nice===sample.nice&&offer.exclude===sample.exclude&&(offer.buyerTypes||[]).join('|')===sample.buyerTypes?.join('|')&&Object.values(offer.advanced||{}).every(v=>!v.trim())&&!offer.roles?.trim();const id=uid();const r:SearchRun={...base,id,status:sampleInput?'Running':'Limited demonstration',stage:0,count:0,rawCount:0,scenario:offer.scenario,budget:offer.scenario==='Exhausted budget'?0:+offer.budget,startedAt:new Date().toISOString(),profileVersion:s.runs.length+1,target:Math.min(24,+offer.target)};setS(x=>({...x,runs:[r,...x.runs],budget:+offer.contacts,discoveryBudget:+offer.budget}));AR(id);clear();go('/app/discover/'+id)}
const currentQuote=s.quotes.find(x=>x.id===quoteId);
useEffect(()=>{if(!currentQuote)return;const delay=Math.max(0,Date.parse(currentQuote.expiresAt)-Date.now());const timer=window.setTimeout(()=>QuoteExpired(true),delay);return()=>window.clearTimeout(timer)},[currentQuote]);
const draft=s.drafts.find(d=>d.id===draftId)||s.drafts[0],dc=s.companies.find(c=>c.id===draft?.buyerId);function editDraft(patch:Partial<OutreachDraft>){if(!draft)return;setS(x=>({...x,drafts:x.drafts.map(d=>d.id===draft.id?{...d,...patch,revision:d.revision+1,status:'Draft',approvedRevision:undefined,approvedAt:undefined}:d)}))}
function requestDemoReview(){if(!draft)return;setS(x=>({...x,drafts:x.drafts.map(d=>d.id===draft.id?{...d,status:'In review',approvedRevision:undefined}:d)}))}
function approveDemoDraft(){if(!draft)return;setS(x=>({...x,drafts:x.drafts.map(d=>d.id===draft.id?{...d,status:'Approved',approvedRevision:d.revision,approver:'Willy Lai',approvedAt:new Date().toISOString()}:d)}))}
function saveDemoDraft(){if(!draft||!draft.recipient.endsWith('.example'))return;const existing=JSON.parse(localStorage.getItem('buyeros-drafts-v1')||'[]');localStorage.setItem('buyeros-drafts-v1',JSON.stringify([...existing.filter((d:OutreachDraft)=>d.id!==draft.id),draft]));toast.success(t('Draft saved on this device.'));closeModal()}
function useSampleProject(){AR('sample-run');closeModal();clear();go('/app/discover')}
function startNewDemoSearch(){closeModal();go('/app/discover/new')}
function confirmDemoQuote(){if(!currentQuote)return;if(Date.parse(currentQuote.expiresAt)<=Date.now()){QuoteExpired(true);toast.error(t('Quote expired'));return}setS(x=>confirm(x,currentQuote.id));QI(null);Modal('');toast.info('Demo lookup processed. Review sample contact statuses.')}
function saveToDemoList(){setS(x=>({...x,lists:x.lists.map(l=>l.id===listId?{...l,members:Array.from(new Set([...l.members,...actionIds]))}:l)}));closeModal();toast.success('Saved to list. Duplicate memberships are ignored.')}
function saveDemoList(){if(modal==='create-list'){const id=uid();setS(x=>({...x,lists:[...x.lists,{...base,id,name:listName.trim(),members:[]}]}));LI(id)}else setS(x=>({...x,lists:x.lists.map(l=>l.id===currentList?.id?{...l,name:listName.trim()}:l)}));closeModal()}
function confirmDemoReason(){if(modal==='reject')reviewed(actionIds,'Rejected',reason);else actionIds.forEach(id=>{const c=s.companies.find(c=>c.id===id)!;update(id,{suppressed:modal==='suppress',contact:modal==='suppress'?'Suppressed':'Not researched',activity:[new Date().toISOString()+' \u00b7 Suppression changed. '+reason,...c.activity]})});closeModal()}
const navTitle=isWizard?'New buyer search':isOverview?'Overview':isLists?'Buyer Lists':isOutreach?'Outreach':isResults?'Results':isSettings?'Settings':isFull?'Buyer profile':'Find Buyers';
const filterFields=<><Pick value={market} onChange={M} items={['All markets','Germany','Netherlands','Belgium']} label={t('All markets')}/><Pick value={type} onChange={T} items={['All buyer types','Distributor','System integrator']} label={t('Buyer type')}/><Pick value={fit} onChange={F} items={['All fit verdicts','Match','Needs review','Not a match']}/><Pick value={review} onChange={R} items={['All reviews','Awaiting review','Accepted','Rejected']}/><Pick value={contact} onChange={C} items={['All contacts','Not researched','Provider-marked valid','Catch-all','Unavailable','Suppressed']}/></>;
function buyerTable(){return <DemoBuyerTable t={t} isLists={isLists} currentListName={currentList?.name}
  rows={rows} pageRows={pageRows} selected={selected} q={q} filterFields={filterFields}
  canApplyPreset={!!preset} sort={sort} optional={optional} page={page} pageCount={pageCount} size={size}
  onSavePreset={()=>{Preset({market,type,fit,review,contact,sourceType,recency});toast.success('Filter preset saved for this session.')}}
  onExport={()=>download('DEMO_buyers.csv',csv(selected.length?selectedRows:rows),'text/csv;charset=utf-8')}
  onQueryChange={Q} onOpenFilters={()=>Filters(true)}
  onApplyPreset={()=>{if(!preset)return;M(preset.market);T(preset.type);F(preset.fit);R(preset.review);C(preset.contact);ST(preset.sourceType);RC(preset.recency)}}
  onSortChange={Sort} onSelectionChange={Sel} onAction={action}
  onRemoveFromList={()=>{setS(x=>({...x,lists:x.lists.map(l=>l.id===currentList?.id?{...l,members:l.members.filter(id=>!selected.includes(id))}:l)}));Sel([])}}
  onOpenBuyer={openBuyer} onClearFilters={clear} onPageSizeChange={Size} onPageChange={P}/>;}
const liveAvailability=availabilityFor(mode,isOverview||isWizard||isBuyers?'overview':'discovery');
return <LocaleContext.Provider value={t}><SidebarProvider open={sidebarOpen} onOpenChange={SidebarOpen} style={{'--sidebar-width':'224px'} as React.CSSProperties}><DemoNavigation t={t} navTitle={navTitle} isWizard={isWizard} isFull={isFull} isSettings={isSettings} go={go} listCount={s.lists.length} spent={u.spent} budget={s.budget} discoveryBudget={s.discoveryBudget} onUsage={()=>RT('Usage')}/><main className="main-shell" data-demo-ready={loaded ? "true" : "false"}><DemoShellHeader t={t} navTitle={navTitle} mode={mode} locale={s.locale} onLocaleChange={locale=>setS(x=>({...x,locale}))}/><div className="content"><DemoRouteHeading t={t} navTitle={navTitle} isWizard={isWizard} isOverview={isOverview} isLists={isLists} isOutreach={isOutreach} isResults={isResults} isSettings={isSettings} isFull={isFull} onProject={()=>Modal('project')} onUseSample={()=>{AR('sample-run');clear();go('/app/discover')}} onNewSearch={()=>go('/app/discover/new')}/>
{mode==='demo'&&(<>{!isOverview&&!isLists&&!isOutreach&&!isResults&&!isSettings&&!isFull&&!isWizard&&<DemoDiscoveryRunView t={t} store={s} run={run} onFitFilter={F} onReviewMatches={()=>{F('Match');R('Awaiting review')}} onCancel={()=>setS(x=>cancelRun(x,run.id))} onRetry={()=>setS(x=>retryRun(x,run.id))} onEditBudget={()=>go('/app/discover/new')} onSelectRun={id=>{AR(id);clear();go('/app/discover/'+id)}}>{buyerTable()}</DemoDiscoveryRunView>}
{isWizard&&<Wizard offer={offer} setOffer={OfferSet} run={startRun} save={()=>{toast.success('Demo draft retained in memory for this session.');go('/app/discover')}} t={t}/>}
{isOverview&&<DemoOverviewView t={t} store={s} pending={u.pending} accepted={u.accepted} runStatus={run.status} onAwaitingReview={()=>{R('Awaiting review');go('/app/discover')}} onAcceptedWithoutContact={()=>{R('Accepted');C('Not researched');go('/app/discover')}} onDraftsInReview={()=>go('/app/outreach')} onCreateProject={()=>go('/app/discover/new')} onContinue={()=>go('/app/discover')}/>}
{isLists&&<><DemoListsView t={t} lists={s.lists} currentListId={currentList?.id} onSelect={id=>{LI(id);go('/app/lists/'+id)}} onCreate={()=>{LN('');Modal('create-list')}} onRename={()=>{LN(currentList?.name||'');Modal('rename-list')}}/>{buyerTable()}</>}
{isFull&&<DemoFullBuyerView buyer={fullBuyer} t={t} action={action} source={Source} update={update} onReturn={()=>go('/app/discover')}/>}
{isOutreach&&<DemoOutreachView t={t} store={s} draft={draft} company={dc} onSelectDraft={DI} onChooseBuyer={()=>{R('Accepted');go('/app/discover')}} onEditDraft={editDraft} onSaveDraft={()=>Modal('save-draft')} onRequestReview={requestDemoReview} onOpenEvidence={Source} onApproveDraft={approveDemoDraft}/>}
{isResults&&<DemoResultsView t={t} store={s} usage={u} tab={resultTab} onTabChange={RT} onOpenBuyer={openBuyer} onRecordOutcome={(buyerId,stage)=>setS(x=>({...x,outcomes:[...x.outcomes.filter(o=>o.buyerId!==buyerId),{...base,id:uid(),buyerId,stage,at:new Date().toISOString()}]}))}/>}
{isSettings&&<DemoSettingsView t={t} store={s} savedLocal={savedLocal}  selectedCompanyId={actionIds[0]||''}  onLocaleChange={locale=>setS(x=>({...x,locale}))}  onDefaultMarketsChange={value=>{setS(x=>({...x,defaultMarkets:value}));OfferSet(o=>({...o,markets:value,confirmed:false}))}}  onBudgetChange={(key,value)=>{if(value<0)return;setS(x=>({...x,[key]:value}));if(key!=='contactUnitPrice')OfferSet(o=>({...o,[key==='budget'?'contacts':'budget']:String(value)}))}}  onSaveLocally={()=>{const clean={...s,companies:s.companies.map(c=>({...c,note:'',owner:'Willy Lai',activity:c.activity.map(a=>a.includes(' \u00b7 Willy Lai:')?a.split('. ')[0]:a)})),drafts:[],lists:s.lists.map((l,i)=>({...l,name:'Saved demo list '+(i+1)})),defaultMarkets:sample.markets};localStorage.setItem('buyeros-demo-v1',JSON.stringify(clean));SL(true);toast.success('Synthetic workflow state saved on this device.')}}  onReset={()=>Reset(true)} onSelectCompany={id=>Ids([id])}  onSuppression={(id,kind)=>{Ids([id]);Modal(kind)}} onConnection={SI}/>}</>)}{mode==='live'&&(isOverview?<><LiveProfilePanel/><LiveOverview/></>:isWizard?(liveAvailability==='available'?<LiveOfferWizard mode="create" onSaved={()=>go('/app')} t={t}/>:<LiveUnavailable state={liveAvailability}/>):isBuyers?(liveAvailability==='available'?<LiveBuyers/>:<LiveUnavailable state={liveAvailability}/>):liveAvailability==='available'?null:<LiveUnavailable state={liveAvailability}/>)}
</div></main><Sheet open={!!buyer} onOpenChange={v=>{if(!v)B(null)}}><SheetContent className="buyer-sheet" onCloseAutoFocus={event=>{if(buyerTriggerRef.current?.isConnected){event.preventDefault();buyerTriggerRef.current.focus()}}}><SheetTitle className="sr-only">{buyer?.name} {t("buyer detail")}</SheetTitle><SheetDescription className="sr-only">{t("Fictional buyer evidence and review")}</SheetDescription>{buyer&&<BuyerDetail c={buyer} t={t} action={action} source={Source} update={update} full={()=>{B(null);go('/app/buyers/'+buyer.id)}}/>}</SheetContent></Sheet><Sheet open={filters} onOpenChange={Filters}><SheetContent className="filter-sheet"><SheetTitle>{t('Filters & view')}</SheetTitle><SheetDescription>{t("Refine the current buyer results.")}</SheetDescription>{filterFields}<Pick value={sourceType} onChange={ST} items={['All sources','Company website','Industry directory','Assessment']}/><Pick value={recency} onChange={RC} items={['Any observation date','Recent sample evidence','Old sample evidence']}/><label className="check-line"><Checkbox checked={optional} onCheckedChange={v=>Optional(!!v)}/>{t("Show owner column")}</label><Button variant="outline" onClick={clear}>{t('Clear filters')}</Button><Button onClick={()=>Filters(false)}>{t("Show")}{rows.length} {t("companies")}</Button></SheetContent></Sheet><DemoSourceDialog source={source} onClose={()=>Source(null)} t={t}/><DemoActionDialog t={t} modal={modal} store={s} actionIds={actionIds}  quote={currentQuote} quoteExpired={quoteExpired} remainingBudget={u.remaining}  draft={draft} selectedListId={listId}  listName={listName} reason={reason} onClose={closeModal}  onSaveDraft={saveDemoDraft} onUseSample={useSampleProject}  onNewSearch={startNewDemoSearch} onConfirmQuote={confirmDemoQuote}  onSelectList={LI} onSaveToList={saveToDemoList}  onListNameChange={LN} onSaveList={saveDemoList}  onReasonChange={Reason} onConfirmReason={confirmDemoReason}/><DemoConnectionDialog connection={settingsInfo} onClose={()=>SI('')} t={t}/><AlertDialog open={reset} onOpenChange={Reset}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{t('Reset demo data')}?</AlertDialogTitle><AlertDialogDescription>{t("This clears BuyerOS demo keys, session edits and synthetic workflow state. Other browser storage is untouched.")}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{t('Cancel')}</AlertDialogCancel><AlertDialogAction onClick={()=>{localStorage.removeItem('buyeros-demo-v1');localStorage.removeItem('buyeros-prefs-v1');localStorage.removeItem('buyeros-drafts-v1');setS(seed());AR('sample-run');OfferSet({...sample});Sel([]);B(null);DI(null);SL(false);clear();go('/app/discover')}}>{t("Reset demo")}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog><Toaster richColors position="bottom-right"/></SidebarProvider></LocaleContext.Provider>}
